#! /bin/bash
#    Copyright (c) 2026
#
#    This file is part of VTless.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

mkdir -p /var/lib/divert-distrib

#2 arguments: The first argument is the file to redirect, the second argument is where to redirect the file to
function DivertDpkgFile
{
  SourceFile="$1"
  DivertDestination="$2"

  DivertPackage=$(dpkg-divert --listpackage "$SourceFile")
  if [[ "$DivertPackage" != "$DPKG_MAINTSCRIPT_PACKAGE" ]]
  then
    dpkg-divert --package "$DPKG_MAINTSCRIPT_PACKAGE" --add --rename --divert "$DivertDestination" "$SourceFile"
  fi
}

DivertDpkgFile /usr/bin/plymouth           /var/lib/divert-distrib/usr_bin_plymouth
